import { it,expect } from 'vitest';
import WebSocket from 'ws';
import { BamiBridge } from '../bridge/src/server.js';
import { SourceAdapter } from '../bridge/src/adapters/adapter.js';
import { newToken } from '../bridge/src/auth.js';
import { Replica } from '../bridge/src/reducer.js';
const adapter:SourceAdapter={source:{adapterId:'fixture',sourceMode:'mock',sourceSessionId:'fixture'},start(emit){emit({type:'source.status',payload:{state:'demo',lastObservedAt:new Date().toISOString(),detail:'fixture'}})},stop(){}};
function open(port:number,token:string){return new Promise<WebSocket>((resolve,reject)=>{const w=new WebSocket(`ws://127.0.0.1:${port}/v1/events`,{headers:{Authorization:'Bearer '+token}});w.once('open',()=>resolve(w));w.once('error',reject);})}
function hello(ws:WebSocket,resume:any=null){ws.send(JSON.stringify({schemaVersion:2,type:'client.hello',clientInstanceId:'fixture',resume,capabilities:['snapshot-v2','message-revisions-v1','chunk-v1']}));}
function next(ws:WebSocket,predicate:(e:any)=>boolean){return new Promise<any>((resolve,reject)=>{const timer=setTimeout(()=>{ws.off('message',listener);reject(Error('EVENT_TIMEOUT'))},3000);const listener=(raw:any)=>{const e=JSON.parse(raw.toString());if(predicate(e)){clearTimeout(timer);ws.off('message',listener);resolve(e)}};ws.on('message',listener);})}
it('authenticates, sends a real snapshot, resumes within bounds, rotates token and preserves source state',async()=>{const token=newToken(),bridge=new BamiBridge(adapter,token);const port=await bridge.start(0);try{await expect(open(port,'bad')).rejects.toThrow();const w=await open(port,token),p=next(w,e=>e.type==='state.snapshot');hello(w);const snap=await p;expect(snap.payload.sourceStatus.state).toBe('demo');const health=await fetch(`http://127.0.0.1:${port}/healthz`);expect(await health.json()).toEqual({ok:true});w.close();const e=bridge.emit({type:'message.completed',conversationId:'fixture',payload:{messageId:'one',role:'assistant',revision:1,content:'🌙',completedAt:new Date().toISOString()}});const w2=await open(port,token);const resumed=next(w2,v=>v.eventId===e.eventId);hello(w2,{streamId:bridge.streamId,lastAppliedSeq:snap.seq});expect((await resumed).payload.content).toBe('🌙');const closed=new Promise<number>(r=>w2.once('close',r));const replacement=newToken();bridge.rotateToken(replacement);expect(await closed).toBe(1008);await expect(open(port,token)).rejects.toThrow();expect(bridge.state.messages[0]!.content).toBe('🌙');const w3=await open(port,replacement);w3.close();}finally{await bridge.stop()}});
it('rejects bad client versions before transmitting conversations',async()=>{const token=newToken(),b=new BamiBridge(adapter,token);const p=await b.start(0);try{const w=await open(p,token);let messages=0;w.on('message',()=>messages++);const closed=new Promise<number>(r=>w.once('close',r));w.send('{"schemaVersion":1,"type":"client.hello"}');expect(await closed).toBe(1008);expect(messages).toBe(0)}finally{await b.stop()}});
it('labels manual input honestly and closes a congested client without discarding source state',async()=>{const manual:SourceAdapter={...adapter,source:{adapterId:'fixture-manual',sourceMode:'manual',sourceSessionId:'fixture'}};const token=newToken(),bridge=new BamiBridge(manual,token);const port=await bridge.start(0);try{bridge.emit({type:'source.status',payload:{state:'live',lastObservedAt:new Date().toISOString(),detail:'fixture'}});expect(bridge.state.sourceStatus.state).toBe('manual');const ws=await open(port,token),snapshot=next(ws,e=>e.type==='state.snapshot');hello(ws);await snapshot;const peer=[...bridge.wss.clients][0]!;Object.defineProperty(peer,'bufferedAmount',{get:()=>10*1024*1024});const closed=new Promise<number>(r=>ws.once('close',r));bridge.emit({type:'message.completed',conversationId:'fixture',payload:{messageId:'retained',role:'assistant',revision:1,content:'복구할 내용',completedAt:new Date().toISOString()}});expect(await closed).toBe(1013);expect(bridge.state.messages[0]?.content).toBe('복구할 내용')}finally{await bridge.stop()}});
