import {describe,it,expect} from 'vitest';
import {readFileSync} from 'node:fs';
import {WeatherStore,normalizeWeather,weatherSchema,weatherUrl,WEATHER_STALE,WEATHER_EXPIRED} from '../bridge/src/weather.js';
import {BamiBridge} from '../bridge/src/server.js';
import {newToken} from '../bridge/src/auth.js';
import {SourceAdapter} from '../bridge/src/adapters/adapter.js';
const fixture=()=>JSON.parse(readFileSync(new URL('../protocol/fixtures/weather-api-zero.json',import.meta.url),'utf8'));
const timestamp=Date.parse('2026-10-03T06:45:00Z');
describe('regional model weather cache',()=>{
 it('keeps zero and null distinct, verifies units and uses source time independently of fetch time',()=>{const raw=fixture();const r=normalizeWeather(raw);expect(r).toMatchObject({temperatureC:0,precipitationMm:0,windMs:0,isDay:false,validAt:'2026-10-03T06:45:00.000Z'});raw.current.temperature_2m=null;expect(normalizeWeather(raw).temperatureC).toBeNull();raw.current_units.wind_speed_10m='km/h';expect(()=>normalizeWeather(raw)).toThrow()});
 it('only polls explicitly, serializes reads, retains last success on failure and ages the data',async()=>{let now=timestamp+1000,calls=0,fail=false;const store=new WeatherStore(async()=>{calls++;if(fail)throw Error('NETWORK');await new Promise(r=>setTimeout(r,5));return fixture()},()=>now);expect(store.snapshot().status).toBe('unavailable');await Promise.all([store.refresh(),store.refresh()]);expect(calls).toBe(1);const saved=store.snapshot();expect(saved.fetchedAt).not.toBe(saved.reading!.validAt);fail=true;await store.refresh();expect(store.snapshot()).toMatchObject({reading:saved.reading,fetchedAt:saved.fetchedAt,status:'stale',error:'NETWORK'});now+=WEATHER_STALE;expect(store.snapshot().status).toBe('stale');now+=WEATHER_EXPIRED;expect(store.snapshot().reading).toEqual(saved.reading);expect(calls).toBe(2);store.stop()});
 it('rejects unknown codes, stale source data, daily mismatch and malformed values without replacing good data',async()=>{let raw=fixture();const store=new WeatherStore(async()=>raw,()=>timestamp);await store.refresh();const good=store.snapshot().reading;for(const change of [(r:any)=>{r.current.weather_code=900},(r:any)=>{r.current.relative_humidity_2m=200},(r:any)=>{r.daily.time[0]='2026-10-04'},(r:any)=>{r.current.time='2026-10-03T12:00'}]){raw=fixture();change(raw);await store.refresh();expect(store.snapshot()).toMatchObject({reading:good,error:'INVALID_RESPONSE'})}store.stop()});
 it('reads shared golden values and requests only the fixed keyless region',()=>{for(const name of ['weather-ready-zero','weather-unavailable']){weatherSchema.parse(JSON.parse(readFileSync(new URL('../protocol/fixtures/'+name+'.json',import.meta.url),'utf8')))}const u=new URL(weatherUrl());expect(u.origin).toBe('https://api.open-meteo.com');expect(u.searchParams.get('latitude')).toBe('37.5665');expect(u.searchParams.get('timezone')).toBe('Asia/Seoul');expect(u.searchParams.get('wind_speed_unit')).toBe('ms');expect(u.searchParams.has('apikey')).toBe(false)});
 it('authenticates weather reads, never mutates conversation seq, and rejects writes',async()=>{const a:SourceAdapter={source:{adapterId:'weather-fixture',sourceMode:'mock',sourceSessionId:'fixture'},start(){},stop(){}};const token=newToken(),bridge=new BamiBridge(a,token),port=await bridge.start(0);try{const base=`http://127.0.0.1:${port}`;expect((await fetch(base+'/v1/weather')).status).toBe(401);const headers={Authorization:'Bearer '+token};const seq=bridge.seq;expect((await fetch(base+'/v1/capabilities',{headers})).status).toBe(200);expect((await fetch(base+'/v1/capabilities',{headers}).then(r=>r.json()) as any).weather).toBe(true);const w=await fetch(base+'/v1/weather',{headers}).then(r=>r.json());expect(weatherSchema.parse(w).status).toBe('unavailable');expect(bridge.seq).toBe(seq);expect((await fetch(base+'/v1/weather',{method:'POST',headers})).status).toBe(405)}finally{await bridge.stop()}});
});
