import { describe,it,expect } from 'vitest';
import { randomUUID } from 'node:crypto';
import { eventSchema,initialState,Event,wireFrames,LIMITS,inputSchema,unknownMetric } from '../bridge/src/protocol.js';
import { reduce,Replica,ResyncRequired } from '../bridge/src/reducer.js';
import { ReplayBuffer } from '../bridge/src/replay-buffer.js';
import { config } from '../bridge/src/config.js';
const streamId=randomUUID(),source={adapterId:'fixture',sourceMode:'mock' as const,sourceSessionId:'fixture'};
function event(type:Event['type'],seq:number,payload:any,extra:any={}):Event{return {schemaVersion:2,streamId,eventId:randomUUID(),seq,timestamp:new Date().toISOString(),source,type,conversationId:'c',taskId:'t',payload,...extra};}
function snapshot(seq=1):Event{return event('state.snapshot',seq,{...initialState(),snapshotId:randomUUID(),asOfSeq:seq});}
const start=(seq=2,revision=1)=>event('message.start',seq,{messageId:'m',role:'assistant',revision});
const delta=(seq=3,index=0,text='형아 🌙',revision=1)=>event('message.delta',seq,{messageId:'m',role:'assistant',revision,deltaIndex:index,text,isFinal:false});
const completed=(seq=4,revision=1,content='형아 🌙')=>event('message.completed',seq,{messageId:'m',role:'assistant',revision,content,completedAt:new Date().toISOString()});
describe('Bami event contracts and replica',()=>{
 it('rejects bad versions, enums, extra fields, missing routing and mismatched snapshot sequence',()=>{expect(eventSchema.safeParse({...snapshot(),schemaVersion:1}).success).toBe(false);expect(eventSchema.safeParse({...snapshot(),secret:'x'}).success).toBe(false);expect(eventSchema.safeParse({...start(),conversationId:undefined}).success).toBe(false);expect(eventSchema.safeParse({...snapshot(),seq:2}).success).toBe(false);expect(inputSchema.safeParse({type:'chat.send',payload:{}}).success).toBe(false);expect(()=>config(['--host','0.0.0.0'])).toThrow('LOOPBACK_ONLY')});
 it('deduplicates completion and snapshot without increasing bubble count',()=>{const r=new Replica();r.apply(snapshot());r.apply(start());r.apply(delta());const c=completed();r.apply(c);expect(r.apply(c)).toBe(false);r.apply(completed(5));expect(r.state.messages).toHaveLength(1);expect(r.state.messages[0]!.content).toBe('형아 🌙');expect(r.apply(snapshot(5))).toBe(false)});
 it('holds last consistent seq when sequence or delta is missing',()=>{const r=new Replica();r.apply(snapshot());r.apply(start());expect(()=>r.apply(delta(4))).toThrow(ResyncRequired);expect(r.seq).toBe(2);expect(()=>r.apply(delta(3,1))).toThrow('DELTA_GAP');expect(r.seq).toBe(2);r.apply(delta());expect(r.seq).toBe(3)});
 it('replaces atomically on new generation and rejects unexpected old-generation events',()=>{const r=new Replica();r.apply(snapshot());r.apply(start());r.apply({...snapshot(),streamId:randomUUID()});expect(r.state.messages).toHaveLength(0);expect(()=>r.apply(delta())).toThrow('STREAM_CHANGED')});
 it('uses authoritative complete, ignores late deltas and applies higher revision edits',()=>{const r=new Replica();r.apply(snapshot());r.apply(start());r.apply(completed(3));r.apply(delta(4,0,'late'));r.apply(event('message.upsert',5,{messageId:'m',role:'assistant',revision:2,content:'수정 🌻',completedAt:new Date().toISOString()}));r.apply(delta(6,0,'old',1));expect(r.state.messages[0]!.content).toBe('수정 🌻')});
 it('preserves Korean and emoji across independent UTF-8 deltas',()=>{const r=new Replica();r.apply(snapshot());r.apply(start());r.apply(delta(3,0,'형아, '));r.apply(delta(4,1,'🌙 한글'));expect(r.state.messages[0]!.content).toBe('형아, 🌙 한글')});
 it('keeps B running when A completes and keeps waiting_user separately',()=>{let s=initialState();for(const [id,status] of [['A','completed'],['B','running'],['C','waiting_user']])s=reduce(s,event('task.upsert',1,{status,phase:'working',publicSummary:id,priority:50,updatedAt:new Date().toISOString()},{taskId:id}));expect(s.tasks.filter(t=>t.status==='running').map(t=>t.taskId)).toEqual(['B']);expect(s.tasks.some(t=>t.status==='waiting_user')).toBe(true)});
 it('distinguishes unknown, zero, manual and stale usage',()=>{const s=reduce(initialState(),event('usage.update',1,{usage:{inputTokens:{...unknownMetric(),knowledge:'known',value:0,freshness:'manual',origin:'user',scope:'session'},outputTokens:{...unknownMetric(),freshness:'stale'}},quotas:[]}));expect(s.usage.inputTokens.value).toBe(0);expect(s.usage.outputTokens.value).toBeNull();expect(s.usage.inputTokens.freshness).toBe('manual')});
 it('bounds message retention and exposes truncation',()=>{let s=initialState();for(let i=0;i<510;i++)s=reduce(s,{...completed(1,1,'x'),payload:{...completed().payload,messageId:'m'+i}});expect(s.messages).toHaveLength(500);expect(s.history.truncated).toBe(true)});
 it('reassembles large emoji snapshot bytes within frame bounds',()=>{const e=completed(1,1,'한글🌙'.repeat(70000));const frames=wireFrames(e);expect(frames.length).toBeGreaterThan(1);frames.forEach(f=>expect(Buffer.byteLength(f)).toBeLessThanOrEqual(LIMITS.frame));const bytes=Buffer.concat(frames.map(f=>Buffer.from(JSON.parse(f).data,'base64')));expect(JSON.parse(bytes.toString()).payload.content).toBe(e.payload.content);expect(()=>wireFrames(completed(1,1,'x'.repeat(LIMITS.logical)))).toThrow('LOGICAL_LIMIT')});
 it('bounds replay by age, bytes/count and returns snapshot indication for expired gap',()=>{let now=0;const b=new ReplayBuffer({count:2,bytes:10000,age:100},()=>now);b.push(start(1));b.push(delta(2));b.push(completed(3));expect(b.after(streamId,0,3)).toBeNull();expect(b.after(streamId,1,3)?.map(e=>e.seq)).toEqual([2,3]);now=101;expect(b.after(streamId,1,3)).toBeNull();expect(b.bytes).toBe(0)});
 it('bounds escaped chat snapshot bytes and rejects unrepresentable Android values',()=>{let s=initialState();for(let i=0;i<4;i++)s=reduce(s,{...completed(1,1,'\\'.repeat(1024*1024)),payload:{...completed(1,1,'\\'.repeat(1024*1024)).payload,messageId:'escaped'+i}});expect(Buffer.byteLength(JSON.stringify(s.messages))).toBeLessThanOrEqual(LIMITS.messageBytes);expect(s.history.truncated).toBe(true);expect(eventSchema.safeParse(start(1,2147483648)).success).toBe(false);expect(eventSchema.safeParse(event('task.upsert',1,{status:'running',phase:'working',publicSummary:'🌙'.repeat(1500),priority:50,updatedAt:new Date().toISOString()})).success).toBe(false)});
});
