import {it,expect,beforeEach,afterEach} from 'vitest';
import net from 'node:net';
import http from 'node:http';
import {randomUUID} from 'node:crypto';
import {readFileSync} from 'node:fs';
import WebSocket from 'ws';
import {BamiBridge} from '../bridge/src/server.js';
import {TailscaleGateway,proxyPeer,canonicalIp} from '../bridge/src/gateway.js';
import {MediaStore} from '../bridge/src/media.js';
import {newToken} from '../bridge/src/auth.js';
import {ObservationTracker} from '../bridge/src/browser/tracker.js';
const host='fixture.tailnet.ts.net:8788',key=newToken(),token=newToken(),id=randomUUID();
function prelude(ip='100.64.0.10') {const v6=ip.includes(':');const b=Buffer.alloc(v6?52:28);Buffer.from('0d0a0d0a000d0a515549540a','hex').copy(b);b[12]=0x21;b[13]=v6?0x21:0x11;b.writeUInt16BE(v6?36:12,14);if(v6)ip.replace('::',':'+Array(8-ip.split(':').filter(Boolean).length).fill('0').join(':')+':').split(':').forEach((n,i)=>b.writeUInt16BE(parseInt(n||'0',16),16+i*2));else ip.split('.').forEach((n,i)=>b[16+i]=Number(n));return b;}
let bridge:BamiBridge,gateway:TailscaleGateway,port:number,sends:number,asset:string;
beforeEach(async()=>{sends=0;const media=new MediaStore();asset=media.put(readFileSync('tests/fixtures/bami-image.png')).assetId!;const tracker=new ObservationTracker();let emit:any;const adapter={source:{adapterId:'wireless-fixture',sourceMode:'mock' as const,sourceSessionId:null},start(e:any){emit=e;emit(tracker.observe({id:'fixed',role:'assistant',content:'합성 한글 🌙',sourceTimestamp:null,images:[]}))},stop(){},async refresh(){const e=tracker.observe({id:'fixed',role:'assistant',content:'수정된 합성 한글 🌙',sourceTimestamp:null,images:[]});if(e)emit(e);return {observedAt:new Date().toISOString()}},async sendPreset(){sends++;return {status:'confirmed' as const,messageId:'synthetic-command'}}};bridge=new BamiBridge(adapter,token,media,{serverId:id,gateway:{host,key}});await bridge.start(0);gateway=new TailscaleGateway(bridge.port,host,key,['100.64.0.10','fd7a:115c:a1e0::10']);port=await gateway.start(0)});
afterEach(async()=>{await gateway.stop();await bridge.stop()});
async function raw(path:string,options:{ip?:string,headers?:Record<string,string>,body?:unknown,fragment?:boolean,proxy?:boolean}={}){return new Promise<Buffer>((resolve,reject)=>{const socket=net.connect(port,'127.0.0.1');let result=Buffer.alloc(0);const timer=setTimeout(()=>{socket.destroy();reject(Error('TIMEOUT'))},2500);socket.on('data',b=>result=Buffer.concat([result,b]));socket.on('error',reject);socket.on('close',()=>{clearTimeout(timer);resolve(result)});socket.on('connect',()=>{const body=options.body?JSON.stringify(options.body):'';const headers={Host:host,Authorization:'Bearer '+token,Connection:'close',...(body?{'Content-Type':'application/json','Content-Length':String(Buffer.byteLength(body))}:{}),...options.headers};const request=Buffer.from(`${body?'POST':'GET'} ${path} HTTP/1.1\r\n`+Object.entries(headers).map(([k,v])=>`${k}: ${v}\r\n`).join('')+'\r\n'+body);const pp=options.proxy===false?Buffer.alloc(0):prelude(options.ip);if(options.fragment){socket.write(pp.subarray(0,8));setTimeout(()=>socket.write(Buffer.concat([pp.subarray(8),request])),10)}else socket.write(Buffer.concat([pp,request]));})})}
function body(b:Buffer){return b.subarray(b.indexOf('\r\n\r\n')+4)}
it('accepts only strict, bounded fragmented TCP PROXY v2 with canonical peer addresses',()=>{expect(proxyPeer(prelude().subarray(0,8))).toBeNull();expect(proxyPeer(prelude())?.ip).toBe('100.64.0.10');expect(canonicalIp('fd7a:115c:a1e0::10')).toBe('fd7a:115c:a1e0::10');const b=prelude();b[12]=0x20;expect(()=>proxyPeer(b)).toThrow('PROXY_REQUIRED');b[12]=0x21;b.writeUInt16BE(217,14);expect(()=>proxyPeer(b)).toThrow('PROXY_LIMIT');expect(()=>canonicalIp('not-an-ip')).toThrow()});
it('passes authenticated capabilities through a split prelude and keeps stable server identity',async()=>{const result=await raw('/v1/capabilities',{fragment:true});expect(result.toString()).toContain('200 OK');expect(result.toString()).toContain(id);const local=await fetch(`http://127.0.0.1:${bridge.port}/v1/capabilities`,{headers:{Authorization:'Bearer '+token}});expect(await local.json()).toMatchObject({serverId:id,presetMessages:true,sync:true})});
it('permits the selected IPv6 tablet peer',async()=>{expect((await raw('/healthz',{ip:'fd7a:115c:a1e0::10'})).toString()).toContain('200 OK')});
it('rejects other peers even when forwarding and gateway headers are forged',async()=>{expect((await raw('/healthz',{ip:'100.12.34.56',headers:{'X-Forwarded-For':'100.64.0.10','X-Bami-Gateway':'Bearer '+key}})).length).toBe(0)});
it('requires PROXY transport and blocks wrong Host, Origin and URL-token paths',async()=>{expect((await raw('/healthz',{proxy:false})).length).toBe(0);for(const o of [{headers:{Host:'evil.ts.net'}},{headers:{Origin:'https://chatgpt.com'}}])expect((await raw('/healthz',o)).toString()).toContain('403');expect((await raw('/v1/events?token=x')).toString()).toContain('403')});
it('keeps app authentication on every protected HTTP route and delivers exact PNG bytes',async()=>{for(const path of ['/v1/weather','/v1/capabilities','/v1/media/'+asset,'/v1/sync','/v1/preset-messages'])expect((await raw(path,{headers:{Authorization:'Bearer '+newToken()}})).toString()).toContain('401');expect(body(await raw('/v1/media/'+asset))).toEqual(readFileSync('tests/fixtures/bami-image.png'))});
it('does not allow public Host directly on the bridge or spoofed internal gateway headers',async()=>{const url=`http://127.0.0.1:${bridge.port}/v1/capabilities`;for(const headers of [{Host:host},{Host:host,'X-Bami-Gateway':'Bearer forged'},{'X-Bami-Gateway':'Bearer '+key}])expect(await new Promise<number>(r=>{http.get(url,{headers:{...headers,Authorization:'Bearer '+token}},res=>{res.resume();r(res.statusCode!)});})).toBe(401)});
it('serializes presets/sync and retains command idempotency over the gateway',async()=>{const commandId=randomUUID();for(let n=0;n<2;n++)expect((await raw('/v1/preset-messages',{body:{commandId,presetId:'thanks'}})).toString()).toContain('confirmed');expect(sends).toBe(1);expect((await raw('/v1/sync',{body:{commandId:randomUUID()}})).toString()).toContain('asOfSeq');expect(bridge.state.messages).toHaveLength(1);expect(bridge.state.messages[0].content).toBe('수정된 합성 한글 🌙')});
it('streams authenticated v2 WS and snapshot through the same ingress',async()=>{const socket=net.connect(port,'127.0.0.1');socket.write(prelude());const ws=new WebSocket(`ws://${host}/v1/events`,{headers:{Authorization:'Bearer '+token},createConnection:()=>socket});try{await new Promise<void>((r,j)=>{ws.once('open',()=>{ws.send(JSON.stringify({schemaVersion:2,type:'client.hello',clientInstanceId:randomUUID(),resume:null,capabilities:['snapshot-v2','message-revisions-v1']}));});ws.on('message',b=>{const e=JSON.parse(b.toString());if(e.type==='state.snapshot'){expect(e.payload.messages).toHaveLength(1);r()}});ws.once('error',j);setTimeout(()=>j(Error('WS_TIMEOUT')),2500).unref()})}finally{ws.terminate()}});
