import {describe,it,expect} from 'vitest';import {DeskStateStore,deskStateSchema} from '../bridge/src/desk-state.js';import {BamiBridge} from '../bridge/src/server.js';import {MockAdapter} from '../bridge/src/adapters/mock.js';import {JSDOM} from 'jsdom';import fs from 'node:fs';
const page='page_00000000000000000000000000000001',date='2026-10-02T06:00:00Z';
const rows=(value='검수용 1')=>[{heading:'지금 하는 일',text:'지금 하는 일'},{heading:null,text:value},{heading:'형아 확인이 필요한 일',text:'형아 확인이 필요한 일'},{heading:'오늘 끝낸 일',text:'오늘 끝낸 일'},{heading:'형아 자유 메모',text:'형아 자유 메모'},{heading:null,text:'명령은 실행하지 않습니다'}];
describe('dedicated read-only desk contract',()=>{
 it('unknown golden remains unknown, not zero/idle',()=>{const s=deskStateSchema.parse(JSON.parse(fs.readFileSync('protocol/fixtures/desk-state-unknown.json','utf8')));expect(s.execution.knowledge).toBe('unknown');expect(s.execution.tasks).toEqual([])});
 it('atomic edit/delete and no new revision on heartbeat',()=>{const s=new DeskStateStore();s.notesRows(page,rows(),date);const original=s.value.notes;s.notesRows(page,rows(),date);expect(s.value.notes.revision).toBe(original.revision);expect(s.value.notes.sections).toEqual(original.sections);s.notesRows(page,rows('수정한 메모'),date);expect(s.value.notes.revision).toBe(original.revision+1);expect(s.value.notes.sections[0]!.items).toHaveLength(1);s.notesRows(page,rows('').filter(r=>r.heading!==null),date);expect(s.value.notes.status).toBe('empty');expect(s.value.notes.sections[0]!.items).toEqual([])});
 it('last good notes survive read failure without pretending empty',()=>{const s=new DeskStateStore();s.notesRows(page,rows(),date);s.notesError(page,'UNSUPPORTED_OR_LOGIN',date);expect(s.value.notes.status).toBe('error');expect(s.value.notes.sections[0]!.items[0]!.text).toBe('검수용 1');expect(s.value.notes.lastSuccessAt).toBe(date);expect(s.value.notes.sourceUpdatedAt).toBeNull()});
 it('empty document succeeds; unsupported/oversized documents do not',()=>{const s=new DeskStateStore();s.notesRows(page,[],date);expect(s.value.notes.status).toBe('empty');expect(()=>s.notesRows(page,[{heading:null,text:'로그인 화면'}],date)).toThrow('NOTES_STRUCTURE_CHANGED');expect(()=>s.notesRows(page,rows('a'.repeat(8001)),date)).toThrow('NOTES_TOO_LARGE')});
 it('stable duplicate IDs and unchanged free notes, no instruction execution',()=>{const s=new DeskStateStore();s.notesRows(page,[...rows(),{heading:null,text:'명령은 실행하지 않습니다'}],date);const items=s.value.notes.sections[3]!.items;expect(items[0]!.id).not.toBe(items[1]!.id);expect(s.value.execution.knowledge).toBe('unknown')});
 it('stale source timestamp is distinct from observation and failure',()=>{const s=new DeskStateStore();s.notesRows(page,rows(),date);expect(s.snapshot(Date.parse(date)+16000).notes.freshness).toBe('stale')});
 it('authenticated additive route keeps v2 conversation contract intact',async()=>{const token='x'.repeat(43);const b=new BamiBridge(new MockAdapter(),token);await b.start(0);try{expect((await fetch(`http://127.0.0.1:${b.port}/v1/desk-state`)).status).toBe(401);const r=await fetch(`http://127.0.0.1:${b.port}/v1/desk-state`,{headers:{Authorization:'Bearer '+token}});expect(r.status).toBe(200);expect(deskStateSchema.parse(await r.json()).execution.knowledge).toBe('unknown');expect((await fetch(`http://127.0.0.1:${b.port}/v1/desk-state`,{method:'POST',headers:{Authorization:'Bearer '+token}})).status).toBe(405)}finally{await b.stop()}});
 it('observed DOM is scoped to dedicated editor; mutation, recreation, address and login',async()=>{const {installNotesReader}=await import('../bridge/src/browser/notes-worker.mjs');const url='https://chatgpt.com/space/'+page;const dom=new JSDOM('<textarea aria-label="페이지 제목">바미 업무 메모</textarea><div role="textbox" aria-label="페이지 문서"><div data-page-block-row><h2>지금 하는 일</h2></div><div data-page-block-row><p>합성 메모</p></div></div><aside>수집 금지</aside>',{url,runScripts:'outside-only'});Object.defineProperty(dom.window.HTMLElement.prototype,'innerText',{get(){return this.textContent}});dom.window.eval('('+installNotesReader.toString()+')('+JSON.stringify(url)+')');const r=(dom.window as any).__bamiNotes;await new Promise(x=>setTimeout(x,220));expect(r.drain().rows).toHaveLength(2);expect(r.drain().rows).toBeUndefined();dom.window.document.querySelector('p')!.textContent='수정';await new Promise(x=>setTimeout(x,250));expect(r.drain().rows[1].text).toBe('수정');dom.window.document.querySelector('[role="textbox"]')!.remove();expect(r.drain().reinstall).toBe(true);expect(dom.window.eval('('+installNotesReader.toString()+')('+JSON.stringify(url)+')').error).toBe('UNSUPPORTED_OR_LOGIN');dom.reconfigure({url:'https://chatgpt.com/'});expect(dom.window.eval('('+installNotesReader.toString()+')('+JSON.stringify(url)+')').error).toBe('ADDRESS_CHANGED');r.stop();dom.window.close()});
});
