import { spawn,ChildProcessWithoutNullStreams } from 'node:child_process';
import { Input,unknownMetric } from './protocol.js';
// Official account-only adapter: no threads, turns, process exec, auth file reads, or default content logs.
export class CodexQuotas {
 private child?:ChildProcessWithoutNullStreams;private timer?:NodeJS.Timeout;private timeout?:NodeJS.Timeout;private stopped=false;private seq=1;private pending=new Map<number,(m:any)=>void>();private previous:any[]=[];
 constructor(private emit:(e:Input)=>void){}
 async start(){this.child=spawn('codex',['app-server','--stdio'],{stdio:['pipe','pipe','pipe']});this.child.stderr.on('data',()=>{});this.child.on('error',()=>this.stale());this.child.on('exit',()=>{if(!this.stopped)this.stale()});let buffer='';this.child.stdout.on('data',raw=>{buffer+=raw.toString();if(buffer.length>8*1024*1024){this.child?.kill();this.stale();return}let i;while((i=buffer.indexOf('\n'))>=0){const line=buffer.slice(0,i);buffer=buffer.slice(i+1);try{const m=JSON.parse(line);const done=this.pending.get(m.id);if(done){this.pending.delete(m.id);done(m)}else if(m.method==='account/rateLimits/updated')this.update(m.params)}catch{}}});
 try{await this.rpc('initialize',{clientInfo:{name:'bami-quota-reader',version:'0.1.0'},capabilities:{experimentalApi:false}});this.child.stdin.write('{"method":"initialized"}\n');await this.refresh();this.timer=setInterval(()=>{void this.refresh()},60000)}catch{this.stale()}}
 private rpc(method:string,params?:unknown){return new Promise<any>((resolve,reject)=>{const id=this.seq++;const timer=setTimeout(()=>{this.pending.delete(id);reject(Error('CODEX_QUOTA_TIMEOUT'))},10000);this.pending.set(id,m=>{clearTimeout(timer);if(m.error)reject(Error('CODEX_QUOTA_UNAVAILABLE'));else resolve(m.result)});this.child?.stdin.write(JSON.stringify({id,method,...(params?{params}:{})})+'\n')})}
 private async refresh(){try{this.update(await this.rpc('account/rateLimits/read'))}catch{this.stale()}}
 private update(result:any){const now=new Date().toISOString();const buckets=result.rateLimitsByLimitId??(result.rateLimits?{codex:result.rateLimits}:{});const quotas=[];for(const [id,b] of Object.entries(buckets) as [string,any][]){for(const window of ['primary','secondary']){const q=b[window];if(!q)continue;const used=typeof q.usedPercent==='number'&&q.usedPercent>=0&&q.usedPercent<=100?q.usedPercent:null;quotas.push({knowledge:used===null?'unknown':'known',value:used,origin:'Codex app-server account/rateLimits/read',scope:'account-wide',observedAt:now,freshness:'fresh',resetAt:typeof q.resetsAt==='number'?new Date(q.resetsAt*1000).toISOString():null,unit:'percent used',limitId:id+':'+window,name:(b.limitName??id)+' · '+window,windowDurationMins:q.windowDurationMins??null,usedPercent:used})}}this.previous=quotas;this.emit({type:'usage.update',payload:{usage:{inputTokens:unknownMetric(),outputTokens:unknownMetric()},quotas}})}
 private stale(){if(this.stopped)return;this.emit({type:'usage.update',payload:{usage:{inputTokens:unknownMetric(),outputTokens:unknownMetric()},quotas:this.previous.map(q=>({...q,freshness:'stale'}))}})}
 stop(){this.stopped=true;if(this.timer)clearInterval(this.timer);this.child?.stdin.end();this.child?.kill();this.pending.clear()}
}
