import {spawn,ChildProcessWithoutNullStreams} from 'node:child_process';import {DeskStateStore,Execution} from './desk-state.js';
/** Read-only runtime metadata from an explicitly chosen non-implementation thread.
 * No turn contents, resume/start, prompts, config writes, or inferred completion. */
export class CodexRuntime {
 private child?:ChildProcessWithoutNullStreams;private pending=new Map<number,(m:any)=>void>();private seq=0;private timer?:NodeJS.Timeout;private stopped=false;
 constructor(private store:DeskStateStore,readonly threadId:string){if(!/^[a-f0-9-]{36}$/.test(threadId))throw Error('RUNTIME_TARGET')}
 async start(){this.child=spawn('codex',['app-server','--stdio'],{stdio:'pipe'});let buffer='';this.child.stderr.on('data',()=>{});this.child.on('error',()=>this.unknown());this.child.on('exit',()=>this.unknown());this.child.stdout.on('data',c=>{buffer+=c;if(buffer.length>512*1024){this.child?.kill();return;}let i;while((i=buffer.indexOf('\n'))>=0){try{const m=JSON.parse(buffer.slice(0,i));const done=this.pending.get(m.id);this.pending.delete(m.id);done?.(m)}catch{}buffer=buffer.slice(i+1)}});try{await this.rpc('initialize',{clientInfo:{name:'bami-runtime-reader',version:'1'},capabilities:{experimentalApi:false}});this.child.stdin.write('{"method":"initialized"}\n');await this.refresh();this.timer=setInterval(()=>void this.refresh(),5000)}catch{this.unknown()}}
 private rpc(method:string,params:unknown){return new Promise<any>((resolve,reject)=>{const id=++this.seq;const timer=setTimeout(()=>{this.pending.delete(id);reject(Error('RUNTIME_UNAVAILABLE'))},4000);this.pending.set(id,m=>{clearTimeout(timer);if(m.error)reject(Error('RUNTIME_UNAVAILABLE'));else resolve(m.result)});this.child?.stdin.write(JSON.stringify({id,method,params})+'\n')})}
 private unknown(){if(this.stopped)return;const old=this.store.value.execution;this.store.execution({...old,knowledge:'unknown',source:'codex-app-server',freshness:old.observedAt?'stale':'unknown',reason:'TARGET_RUNTIME_UNAVAILABLE'})}
 private async refresh(){if(this.stopped)return;try{const r=await this.rpc('thread/read',{threadId:this.threadId,includeTurns:false});const s=r.thread?.status;const now=new Date().toISOString();const state=s?.type==='active'?s.activeFlags?.some((f:string)=>['waitingOnApproval','waitingOnUserInput'].includes(f))?'waiting_user':'working':s?.type==='idle'?'idle':s?.type==='systemError'?'blocked':'unknown';this.store.execution({knowledge:state==='unknown'?'unknown':'known',source:'codex-app-server',observedAt:now,freshness:'fresh',reason:state==='unknown'?'TARGET_NOT_LOADED':'',tasks:[{taskId:this.threadId,state,phase:state==='working'?'working':'none',origin:'codex-app-server',observedAt:now,completionEventId:null}]})}catch{this.unknown()}}
 stop(){this.stopped=true;clearInterval(this.timer);this.child?.stdin.end();this.child?.kill();this.pending.clear()}
}
