import {homedir} from 'node:os';
import path from 'node:path';
import {readFileSync,existsSync} from 'node:fs';
import {z} from 'zod';
export const stateDir=path.join(homedir(),'.local/state/dots-room');
export const defaultTokenFile=path.join(stateDir,'pairing.token');
export const regionSchema=z.object({name:z.string().min(1).max(80),latitude:z.number().finite().min(-90).max(90),longitude:z.number().finite().min(-180).max(180),timezone:z.string().max(100).refine(v=>{try{new Intl.DateTimeFormat('en',{timeZone:v});return true}catch{return false}})}).strict();
export const defaultRegion={name:'서울',latitude:37.5665,longitude:126.9780,timezone:'Asia/Seoul'};
export function validateDotsUrl(raw:string):string {try{const u=new URL(raw);if(u.origin!=='https://chatgpt.com'||u.username||u.password||u.search||u.hash||!/^\/dots\/[a-f0-9]{8}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{12}$/.test(u.pathname))throw Error();return u.href}catch{throw Error('DOTS_URL_REQUIRED_OR_INVALID')}}
export const settingsSchema=z.object({dotsUrl:z.string().default(''),egoBrowser:z.string().min(1).default('ego-browser'),port:z.number().int().min(1024).max(65535).refine(v=>![8765,8787].includes(v)).default(8788),codexQuotas:z.boolean().default(false),notes:z.object({pageId:z.string().regex(/^page_[a-f0-9]{32}$/),spaceId:z.number().int().positive().safe()}).strict().nullable().default(null),weather:regionSchema.default(defaultRegion)}).strict();
export function settings(file=process.env.DOTS_ROOM_CONFIG??path.resolve('config.local.json')){if(!existsSync(file))return settingsSchema.parse({});const b=readFileSync(file);if(b.length>16384)throw Error('CONFIG_TOO_LARGE');try{return settingsSchema.parse(JSON.parse(b.toString('utf8')))}catch{throw Error('CONFIG_INVALID')}}
export function config(args:string[]){const opts:Record<string,string>={};for(let i=0;i<args.length;i+=2){const key=args[i],value=args[i+1];if(!key?.startsWith('--')||!value||!['--host','--port','--adapter','--file','--token-file','--codex-quotas'].includes(key))throw Error('ARGUMENTS');opts[key.slice(2)]=value;}if(opts.host&&opts.host!=='127.0.0.1')throw Error('LOOPBACK_ONLY');const local=settings();const port=Number(opts.port??process.env.BAMI_PORT??local.port);if(!Number.isInteger(port)||port<1024||port>65535||[8765,8787].includes(port))throw Error('PORT');const adapter=opts.adapter??'mock';if(!['mock','manual','file','dots','browser-dots'].includes(adapter))throw Error('ADAPTER');if(adapter==='file'&&!opts.file)throw Error('FILE_REQUIRED');if(opts['codex-quotas']&&!['true','false'].includes(opts['codex-quotas']))throw Error('CODEX_QUOTAS');return {...local,port,adapter,codexQuotas:opts['codex-quotas']?opts['codex-quotas']==='true':local.codexQuotas,file:opts.file,tokenFile:opts['token-file']??defaultTokenFile,dotsUrl:adapter==='browser-dots'?validateDotsUrl(process.env.DOTS_ROOM_URL??local.dotsUrl):local.dotsUrl};}
