package dev.dots.room
import org.junit.Test
import org.junit.Assert.*
import java.time.Instant
class ActualBehaviorTest {
 private val time=Instant.parse("2026-10-02T06:00:00Z")
 private fun task(id:String,state:String,phase:String="none",complete:String?=null)=ExecutionTask(id,state,phase,"fixture",time.toString(),complete)
 private fun desk(vararg tasks:ExecutionTask)=DeskState(execution=ExecutionState("known","fixture",time.toString(),"fresh","",tasks.toList()))
 @Test fun goldenAndUnknownNeverBecomeIdleOrWorkFromWords(){val s=protocolJson.decodeFromString<DeskState>(javaClass.classLoader!!.getResource("desk-state-unknown.json")!!.readText()).validate();assertEquals("unknown",runtimeState(s.execution,true,time));val data=AppState(messages=listOf(Message("word","demo",role="user",revision=1,content="작업해줘 확인할게요")));assertEquals("listening",ActualBehavior.next(data,s,Behavior(),2000,true,time).action)}
 @Test fun simultaneousWorkCompletionAndWaitPriority(){val s=desk(task("a","completed",complete="finish-a"),task("b","working","reading"));var b=ActualBehavior.next(AppState(),s,Behavior(),2000,true,time);assertEquals("celebrate",b.action);assertEquals(1,b.running);b=ActualBehavior.next(AppState(),s,b,3000,true,time);b=ActualBehavior.next(AppState(),s,b,4100,true,time);assertEquals("read",b.action);assertEquals("b",b.taskId);assertEquals(1,b.completedIds.size);assertEquals("listening",ActualBehavior.next(AppState(),desk(task("b","working"),task("wait","waiting_user")),b,4200,true,time).action);assertEquals("confused",ActualBehavior.next(AppState(),desk(task("error","blocked")),b,4200,true,time).action)}
 @Test fun noCompletionWithoutExplicitEventAndImmediateDisconnect(){val b=ActualBehavior.next(AppState(),desk(task("a","completed")),Behavior("work"),3000,true,time);assertNotEquals("celebrate",b.action);assertEquals("listening",ActualBehavior.next(AppState(),desk(task("b","working")),Behavior("work"),3000,false,time).action);assertEquals("unknown",runtimeState(desk(task("b","working")).execution,true,time.plusSeconds(16)))}
 @Test fun debounceAvoidsShortRoundTripsAndSameStateRestart(){val s=desk(task("a","working"));val old=Behavior("listening",since=500);val pending=ActualBehavior.next(AppState(),s,old,1000,true,time);assertEquals("listening",pending.action);val canceled=ActualBehavior.next(AppState(),DeskState(),pending,1400,true,time);assertEquals("listening",canceled.action);val started=ActualBehavior.next(AppState(),s,ActualBehavior.next(AppState(),s,canceled,2000,true,time),3100,true,time);assertEquals("work",started.action);assertEquals(started.since,ActualBehavior.next(AppState(),s,started,5100,true,time).since)}
 @Test fun replyVisualExpiresToUnknownWithoutWorkOrSleep(){val data=AppState(sourceStatus=SourceStatus(state="live"),messages=listOf(Message("reply","browser-visible",role="assistant",revision=1,content="확인할게요",observation=Observation("browser-ui","reply",null,null,time.toString(),null,"local-observation","unknown","none"))));val b=ActualBehavior.next(data,DeskState(),Behavior("listening"),1000,true,time);assertEquals("talk",b.action);val visible=ConversationReaction.speechVisible(b,2000);assertEquals("listening",ActualBehavior.next(data,DeskState(),visible,7100,true,time).action);assertEquals("listening",ActualBehavior.next(data.copy(messages=data.messages.map{it.copy(revision=2)}),DeskState(),visible,7200,true,time).action)}
 @Test fun unavailableSourceDoesNotDecorate(){for(source in listOf("unavailable","stale")){val b=ActualBehavior.next(AppState(sourceStatus=SourceStatus(state=source)),DeskState(),Behavior("read",lifeSince=0,lifeNextAt=0),50000,true,time);assertEquals("listening",b.action);assertEquals("stay",b.ambientTarget)}}
}
