package dev.dots.room

import org.junit.Test
import org.junit.Assert.*
import kotlinx.serialization.json.*
import java.util.UUID
import java.time.ZonedDateTime
import java.time.ZoneId

class BamiStateTest {
 private val stream=UUID.randomUUID().toString()
 private fun event(type:String,seq:Long,payload:JsonObject)=Event(2,stream,UUID.randomUUID().toString(),seq,"2026-09-30T12:00:00.000Z",Source("fixture","mock","fixture"),type,"c","t",payload)
 private fun snapshot(seq:Long=1)=event("state.snapshot",seq,protocolJson.encodeToJsonElement(Snapshot(UUID.randomUUID().toString(),seq,SourceStatus("demo",null,"fixture"),emptyList(),emptyList(),Usage(),emptyList(),History())).jsonObject)
 private fun completed(seq:Long=2,revision:Int=1)=event("message.completed",seq,protocolJson.encodeToJsonElement(Completed("m","assistant",revision,"형아 🌙 한글","2026-09-30T12:00:00.000Z")).jsonObject)
 @Test fun snapshotDuplicateAndRevision(){val r=AppReducer();assertTrue(r.apply(snapshot()));val e=completed();r.apply(e);assertFalse(r.apply(e));assertEquals(1,r.state.messages.size);r.apply(completed(3,2));assertEquals(2,r.state.messages.single().revision);assertEquals("형아 🌙 한글",r.state.messages.single().content)}
 @Test fun gapKeepsConsistentState(){val r=AppReducer();r.apply(snapshot());try{r.apply(completed(3));fail("gap") }catch(_:NeedsResync){};assertEquals(1,r.seq);assertTrue(r.state.messages.isEmpty())}
 @Test fun lateDeltaAndMissingDelta(){val r=AppReducer();r.apply(snapshot());r.apply(event("message.start",2,protocolJson.encodeToJsonElement(Start("m","assistant",1)).jsonObject));try{r.apply(event("message.delta",3,protocolJson.encodeToJsonElement(Delta("m","assistant",1,1,"x",false)).jsonObject));fail("gap")}catch(_:NeedsResync){};assertEquals(2,r.seq);r.apply(completed(3));r.apply(event("message.delta",4,protocolJson.encodeToJsonElement(Delta("m","assistant",1,0,"late",false)).jsonObject));assertEquals("형아 🌙 한글",r.state.messages.single().content)}
 @Test fun multipleTasksAndWaitingDoNotBecomeIdle(){val t=Task("A","c","completed","none","",50,"2026-09-30T12:00:00Z");val s=AppState(sourceStatus=SourceStatus("demo"),tasks=listOf(t,t.copy(taskId="B",status="running",phase="working"),t.copy(taskId="C",status="waiting_user")));val first=BehaviorScheduler.next(s,Behavior(),10,true);assertEquals("celebrate",first.action);val next=BehaviorScheduler.next(s,first,1200,true);assertEquals("work",next.action);assertEquals(1,next.running);assertEquals(1,next.warnings);assertEquals("work",BehaviorScheduler.next(s,next,2500,true).action)}
 @Test fun taskCancelsSleepAndUnknownDoesNotSleep(){val active=AppState(sourceStatus=SourceStatus("live"),tasks=listOf(Task("B","c","running","reading","",50,"2026-09-30T12:00:00Z")));assertEquals("read",BehaviorScheduler.next(active,Behavior("sleep"),200000,true).action);assertEquals("listening",BehaviorScheduler.next(AppState(),Behavior(),200000,false).action)}
 @Test fun usageUnknownIsNotZero(){assertEquals("정보 제공 안 됨",metricText(Metric()));assertEquals("0 tokens · 수동",metricText(Metric("known",0.0,"user","task",freshness="manual")))}
 @Test fun directionAndDiagonalSpeed(){assertEquals("S",Navigation.direction(0f,1f));assertEquals("N",Navigation.direction(0f,-1f));assertEquals("NE",Navigation.direction(1f,-1f));val straight=Navigation.step(Point(0f,0f),Point(100f,0f),.1f);val diagonal=Navigation.step(Point(0f,0f),Point(100f,100f),.1f);assertEquals(straight.x.toDouble(),kotlin.math.hypot(diagonal.x.toDouble(),diagonal.y.toDouble()),.0001)}
 @Test fun collisionsAndBlockedRoute(){val prop=Furniture("wall",listOf(0f,0f,96f,96f),0f,listOf(145f,260f,20f,100f));assertTrue(Navigation.collides(Point(150f,300f),listOf(prop)));val nodes=listOf(Waypoint("a",listOf(100f,300f),listOf("b")),Waypoint("b",listOf(200f,300f),listOf("a")));assertTrue(Navigation.route(Point(100f,300f),"b",nodes,listOf(prop)).isEmpty())}
 @Test fun timezoneMidnightMonthEnd(){val t=ZonedDateTime.parse("2026-09-30T23:59:59+09:00[Asia/Seoul]");assertEquals(10,t.plusSeconds(1).monthValue);assertEquals(1,t.plusSeconds(1).dayOfMonth);assertEquals(30,t.withZoneSameInstant(ZoneId.of("UTC")).dayOfMonth)}
 @Test fun goldenFixturesMatch(){val stream=javaClass.getResourceAsStream("/snapshot.json")?:error("fixture missing");val e=protocolJson.decodeFromString<Event>(stream.bufferedReader().readText());val r=AppReducer();r.apply(e);assertEquals(1,r.state.messages.size);assertEquals("형아 🌙",r.state.messages.single().content)}
 @Test fun calendarLeapYearAndWeekBoundaries(){val feb=calendarCells(java.time.YearMonth.of(2024,2));assertEquals(29,feb.filterNotNull().size);assertEquals(java.time.LocalDate.of(2024,2,1),feb[4]);assertEquals(0,feb.size%7);assertEquals(java.time.LocalDate.of(2026,2,1),calendarCells(java.time.YearMonth.of(2026,2)).first())}
 @Test fun widgetHitRegionsUseManifestIncludingMonitorScreen(){val m=Manifest(1,listOf(384,448),96,"",emptyList(),listOf(Furniture("clock",listOf(37f,43f,57f,57f),100f),Furniture("calendar",listOf(119f,41f,53f,57f),100f),Furniture("desk",listOf(114f,153f,156f,136f),262f,screen=listOf(160f,175f,66f,31f))),emptyList(),TransitionPolicy("anchor-slide",320,emptyList()),"fixture");assertEquals(RoomWidget.CLOCK,roomWidgetAt(m,65f,71f));assertEquals(RoomWidget.CALENDAR,roomWidgetAt(m,145f,74f));assertEquals(RoomWidget.MONITOR,roomWidgetAt(m,193f,190f));assertNull(roomWidgetAt(m,190f,330f));assertNull(roomWidgetAt(m,190f,280f))}
 @Test fun completionHistorySurvivesRemovalAndTimestampUpdates(){val a=Task("A","c","completed","none","",50,"2026-09-30T12:00:00Z");var s=AppState(sourceStatus=SourceStatus("live"),tasks=listOf(a));var b=BehaviorScheduler.next(s,Behavior(),0,true);assertEquals("celebrate",b.action);s=s.copy(tasks=listOf(a,a.copy(taskId="B",updatedAt="2026-09-30T12:01:00Z")));b=BehaviorScheduler.next(s,b,1000,true);assertEquals("B",b.lastCompletion);s=s.copy(tasks=listOf(a.copy(updatedAt="2026-09-30T12:02:00Z")));b=BehaviorScheduler.next(s,b,2000,true);assertNotEquals("celebrate",b.action);assertEquals(listOf("A","B"),b.completedIds)}
 @Test fun unknownTaskHoldsAttentionAlongsideRunningTask(){val u=Task("U","c","unknown","none","",50,"2026-09-30T12:00:00Z");val s=AppState(sourceStatus=SourceStatus("live"),tasks=listOf(u));assertEquals("listening",BehaviorScheduler.next(s,Behavior("sleep"),200000,true).action);val b=BehaviorScheduler.next(s.copy(tasks=listOf(u,u.copy(taskId="R",status="running",phase="working"))),Behavior(),200000,true);assertEquals("work",b.action);assertEquals(1,b.warnings);assertEquals(1,b.running)}
}
