package dev.dots.room
import org.junit.Test
import org.junit.Assert.*
import kotlin.math.*
class RoomInteractionTest {
 private fun manifest()=protocolJson.decodeFromString<Manifest>(javaClass.classLoader!!.getResource("manifest.json")!!.readText())
 @Test fun twoTapsOpenOnlyWithinCuriosityWindow(){val i=RoomInteraction();val p=Point(190f,350f);i.tap(p,0);assertEquals("curious",i.phase);assertTrue(i.freezes);i.tap(p,4900);assertTrue(i.menu);i.close();i.tap(p,0);i.tick(5001,false,null);assertEquals("normal",i.phase);i.tap(p,5002);assertEquals("curious",i.phase)}
 @Test fun busyDropReactsThenResumesLatestWork(){val i=RoomInteraction();i.lift(Point(10f,20f),0);i.release(Placement(Point(190f,350f)),100,true,"request");i.tick(2099,true,"new-request");assertEquals("landing",i.phase);i.tick(2100,true,"new-request");assertFalse(i.freezes)}
 @Test fun idleDropRetainsFurnitureThenReturnsToRoutine(){val i=RoomInteraction();i.release(Placement(Point(190f,292f),"desk"),0,false,null);assertEquals("work",i.action());i.tick(2000,false,null);assertEquals("resting",i.phase);i.tick(22000,false,null);assertEquals("normal",i.phase);i.release(Placement(Point(315f,357f),"bed"),0,false,null);assertEquals("sleep",i.action());i.tick(2000,false,null);i.tick(2100,true,"request");assertFalse(i.freezes)}
 @Test fun realTwoCirclesTriggerButJitterAndBackAndForthDoNot(){val d=CircularDrag();var triggered=false;for(n in 0..80){val a=n*4*PI/80;triggered=triggered||d.add(Point((190+40*cos(a)).toFloat(),(350+40*sin(a)).toFloat()),n*30L)};assertTrue(triggered);d.reset();for(n in 0..120)assertFalse(d.add(Point(190f+(n%2)*2,350f),n*20L));d.reset();for(n in 0..120)assertFalse(d.add(Point(190f+(n%20)*5,350f),n*20L))}
 @Test fun dizzyDropRecoversForFourSeconds(){val i=RoomInteraction();i.lift(Point(190f,350f),0);for(n in 0..80){val a=n*4*PI/80;i.drag(Point((190+40*cos(a)).toFloat(),(350+40*sin(a)).toFloat()),n*30L)};assertTrue(i.dizzy);i.release(Placement(Point(190f,350f)),2500,true,"request");assertEquals("dizzy",i.action());i.tick(6499,true,"request");assertEquals("dizzy",i.phase);i.tick(6500,true,"request");assertEquals("normal",i.phase)}
 @Test fun projectsOntoReachableFloorAndFurnitureAnchors(){val m=manifest();val bed=m.furniture.first{it.id=="bed"};val chair=m.furniture.first{it.id=="chair"};assertEquals("bed",DropPlacement.resolve(Point(bed.rect[0]+bed.rect[2]/2,bed.rect[1]+bed.rect[3]/2),m).furniture);assertEquals("desk",DropPlacement.resolve(Point(chair.rect[0]+chair.rect[2]/2,chair.rect[1]+chair.rect[3]/2),m).furniture);for(p in listOf(Point(0f,0f),Point(190f,240f),Point(400f,460f),Point(190f,300f))){val safe=DropPlacement.resolve(p,m);if(safe.furniture==null){assertFalse(Navigation.collides(safe.point,m.furniture));assertTrue(m.waypoints.any{Navigation.safe(safe.point,Point(it.point[0],it.point[1]),m.furniture)})}}}
 @Test fun placementRestoresValidatedAnchorsAndRearFacingDesk(){val m=manifest();val motion=SceneMotion(m);val p=DropPlacement.restore(Placement(Point(-100f,-100f),"desk"),m);motion.place(p);assertTrue(motion.seatedAtDesk);assertEquals("N",motion.direction);assertEquals(m.furniture.first{it.id=="desk"}.anchor!!.let{Point(it[0],it[1])},motion.position);val restored=DropPlacement.restore(Placement(Point(-10f,900f)),m);assertFalse(Navigation.collides(restored.point,m.furniture))}
}
